// This file is automatically generated by qtc from "hello.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line hello.qtpl:1
package templates

//line hello.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// Main page template. Implements BasePage methods.
//

//line hello.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line hello.qtpl:4
type Hello struct {
	//CTX *fasthttp.RequestCtx
	Vars map[string]interface{}
}

//line hello.qtpl:11
func (p *Hello) StreamBody(qw422016 *qt422016.Writer) {
	//line hello.qtpl:11
	qw422016.N().S(`
	<h1>`)
	//line hello.qtpl:12
	qw422016.E().V(p.Vars["title"])
	//line hello.qtpl:12
	qw422016.N().S(`</h1>
	<div>
		Hello `)
	//line hello.qtpl:14
	qw422016.E().V(p.Vars["name"])
	//line hello.qtpl:14
	qw422016.N().S(`!
	</div>
`)
//line hello.qtpl:16
}

//line hello.qtpl:16
func (p *Hello) WriteBody(qq422016 qtio422016.Writer) {
	//line hello.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line hello.qtpl:16
	p.StreamBody(qw422016)
	//line hello.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line hello.qtpl:16
}

//line hello.qtpl:16
func (p *Hello) Body() string {
	//line hello.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
	//line hello.qtpl:16
	p.WriteBody(qb422016)
	//line hello.qtpl:16
	qs422016 := string(qb422016.B)
	//line hello.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
	//line hello.qtpl:16
	return qs422016
//line hello.qtpl:16
}
